name: Release
on:
  push:
    branches: [master, main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Push tags/releases
      issues: write    # Error notifications,
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMVER_TOKEN }}  
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run typecheck
      - run: bun test --coverage
      - run: bun run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMVER_TOKEN }}
        with:
          working-directory: ./
